### ISSUE TITLE
Doesn't work, want my money back

### ISSUE THREAD

**Issue by alexgleith** [rjhale1971/NAIP_WMS#7]
#gistribe4eva

![image](https://user-images.githubusercontent.com/3445853/41399748-811e63a4-6ffe-11e8-9b18-dcbd83eefbb1.png)

Using the URL: `https://gis.apfo.usda.gov/arcgis/services/NAIP/California_2016_60cm/ImageServer/WMSServer?` doesn't seem to work currently. Is it just me?

**Comment by rjhale1971** [comment]
It's only for 'Murica. 
Actually - that's interesting. So it worked on mine (3.0) - lemme try 2.18. I've had that message before - I'm wondering if it was down earlier.

**Comment by alexgleith** [comment]
Hmm, ok so it does work in QGIS3, but not in QGIS 2.18. Odd!

Seems to be an issue with QGIS anyhow, so I guess you're off the hook ;-)

**Comment by rjhale1971** [comment]
Well - that's not right..... It used to work in 2.18 and not in 3. I actually hadn't worked up the never to start importing them in to fix them...... Shenanigans are afoot.
