### ISSUE TITLE
shutdown affecting NAIP?

### ISSUE THREAD

**Issue by badgley** [rjhale1971/NAIP_WMS#8]
Just wondering if anyone with more experience using NAIP can provide some context.

I tried to connect to the following WMS through QGIS: "https://gis.apfo.usda.gov/arcgis/services/NAIP/Idaho_2015_1m/ImageServer/WMSServer?". I get a Bad request. 

Presently, https://gis.apfo.usda.gov/arcgis/rest/services/NAIP/ only lists the following services: USDA_CONUS_PRIME and NAIP_image_dates. From what I recall, I should also be able to see state level links? 

Just hoping to connect with people who know more about NAIP than I do to see if something changed. Back of my mind is wondering if the servers are offline due to the government shutdown.

**Comment by badgley** [comment]
Read the `README'. Sorry to spam.

second bullet states: "In the case of Government Shutdown these links will not work (which is so unbelievably stupid I hate even typing that)."

**Comment by rjhale1971** [comment]
Hah - Possibly. Let me check them. I was thinking I need to check to make sure the links still work. Sometimes USDA will just move stuff.

**Comment by rjhale1971** [comment]
OK - They've moved all the end points again. I hadn't noticed. Lemme see if I can fix this - it could be a quick fix.

**Comment by badgley** [comment]
@rjhale1971 mind posting an example of where the endpoints are? still having trouble tracking things down.

**Comment by rjhale1971** [comment]
Sorry about that.  Check - there is one XML that loads all the NAIP. See if it works. I'm adding a second XML for the imagery dates.
